---
title: "За нас"
---

### Нашата експертиза е в областите на:

-	идентифициране, анализ и управление на рискове;
-	използване на изкуствен интелект в управленските науки;
-	анализ на макроикономически процеси;
-	анализ на пазари и пазарни структури;
-	оптимизиране на бизнес процеси;
-	създаване на помощни инструменти за управление на компании.

### Нашата цел е дейността на УПИЗ „Количествени методи и моделиране“ да:

-	има видими и измерими ефекти в публичната сфера, да подпомага взимането на решения в бизнеса и политиката и да служи на публичния интерес;
-	да се превърне в център за експертиза в областта на анализа на данни, математическото моделиране, анализа и оценката на рискове, създаването на компютърни приложения;
-	да подпомага практическото обучение на студентите с използването на количествени методи, като популяризира сред тях тези методи, аналитичното мислене и работата с масиви от данни;
-	да се превърне в център за сътрудничество на различни департаменти на НБУ и да привлече външни партньори от бизнеса;
-	с резултатите и популяризирането на методите, дейностите и данните на сайта си, да допълва имиджа на НБУ като място за приложни изследвания.



